enabledEnchants:
  - Goggles
  - Fish
  - Trifecta

enchants:
  Goggles:
    item:
      - DIAMOND_HELMET
    chance:
    lvl_5_chance: 1
    lvl_15_chance: 2
    lvl_30_chance: 3 
    lvl_45_chance: 4
    lvl_60_chance: 5
    lvl_5_maxLevel: 1
    lvl_15_maxLevel: 1
    lvl_30_maxLevel: 1
    lvl_45_maxLevel: 1
    lvl_60_maxLevel: 1
    lore: lore :)
    name: Goggles
  Fish:
    item:
      - DIAMOND_HELMET
    lvl_5_chance: 1
    lvl_15_chance: 0
    lvl_30_chance: 3 
    lvl_45_chance: 4
    lvl_60_chance: 5
    lvl_5_maxLevel: 1
    lvl_15_maxLevel: 0
    lvl_30_maxLevel: 1
    lvl_45_maxLevel: 1
    lvl_60_maxLevel: 1
    lore: lore :)
    name: Fish
  Trifecta:
    item:
    - DIAMOND_HELMET
    lvl_5_chance: 1
    lvl_15_chance: 0
    lvl_30_chance: 3
    lvl_45_chance: 4
    lvl_60_chance: 5
    lvl_5_maxLevel: 1
    lvl_15_maxLevel: 0
    lvl_30_maxLevel: 1
    lvl_45_maxLevel: 1
    lvl_60_maxLevel: 1
    lore: '&eTrifecta'
    name: Trifecta

enchantGui:
  level5-lore: '&eLore'
  level5-name: '&aName'
  level15-name: '&aName'
  level15-lore: '&eLore'
  level30-name: '&aName'
  level30-lore: '&eLore'
  level45-name: '&aName'
  level45-lore: '&eLore'
  level60-lore: '&eLore'
  level60-name: '&aName'
